### ISSUE TITLE
Question on bbduk command usage

### ISSUE THREAD

**Issue by tamuanand** [alesssia/YAMP#13]
Hi

I was just curious about your usage of the bbduk related commands in the [YAMP.nf](https://github.com/alesssia/YAMP/blob/master/YAMP.nf#L401) script 

Just curious - why the use of CMD and why the use of the double quotes on that long command?

Couldn't it have been written as 
```

if ($params.librarylayout == 'paired'){
   bbduk.sh in=read1 in1=read2 ....
}
```

**Comment by alesssia** [comment]
I am saving the command to a variable (`CMD`) to be able to print it into the logs and improve the reproducibility of the pipeline. The double quotes around `$maxmem` (are you referring to those?) are due to the nextflow syntax.
 
If you look at previous versions of the script, you will see that I am running the commands (including bbduk) as you suggested :)

**Comment by tamuanand** [comment]
Thanks for your response. 

You are right: My question was on bbduk usage around maxmem - what was the error that was happening with previous versions..

Sorry - I am a newbie as regards NF - that's why all these questions.

Thanks for your time.

**Comment by alesssia** [comment]
Since you are interested in well-designed NF pipeline, have you had a look at the NF-Core project? https://nf-co.re/
